In [1]:
import numpy as np

list1 = [1, 2, 3, 4]
print(list1)
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)

[1, 2, 3, 4]
<class 'numpy.ndarray'>
[1 2 3 4]


In [6]:
import numpy as np

t1 = np.arange(24).reshape(4, 6)
print(t1)
# 切片
print(t1.shape)
print(t1.dtype)
print(t1.ndim)
print(t1.size)
print(t1[1:])
print(t1[:2, 1:3])
print(t1[[1, 3], [2, 4]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
int64
2
24
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[1 2]
 [7 8]]
[ 8 22]


In [10]:
import numpy as np

t1 = np.arange(24).reshape((2, 3, 4))
print(t1)
print(np.sum(t1, axis=0))
print(np.sum(t1, axis=1))
print(np.sum(t1, axis=2))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


In [18]:
import numpy as np

t1 = np.arange(24).reshape((4, 6))
print(t1)
t1[1, :] = 0
print(t1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [21]:
m = 10 if 10 > 5 else 5
print(m)

10


In [23]:
import numpy as np

t1 = np.arange(24).reshape((4, 6))
print(t1)
t2 = t1.flatten()
print(t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [25]:
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 9, 8, 2])
u, indices = np.unique(a, return_index=True)
print(u)
print(indices)
u, indices = np.unique(a, return_inverse=True)
print(indices)
u, indices = np.unique(a, return_counts=True)
print(indices)

[2 5 6 7 8 9]
[1 0 2 4 8 7]
[1 0 2 0 3 1 2 5 4 0]
[3 2 2 1 1 1]


In [31]:
import numpy as np

score = np.array([[80, 88], [82, 81], [75, 81]])

data = np.max(score)
print(data)

data = np.max(score, axis=0)
print(data)

data = np.maximum([-2, -1, 0, 1, 2], 0)
print(data)

avgNum = np.mean(score)
print(avgNum)
print(np.mean(score, axis=0))

88
[82 88]
[0 0 0 1 2]
81.16666666666667
[79.         83.33333333]


In [35]:
t1 = np.array([[1, 2, 3], [4, 5, 6]])
print(t1)
print(t1.cumsum(0))
print(t1.cumsum(1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


In [40]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

t1 = np.concatenate((a, b), axis=0)
print(t1)
t2 = np.concatenate((a, b), axis=1)
print(t2)

t3 = np.stack((a, b), axis=0)
print(t3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
print(np.vstack((v1, v2)))
print(np.hstack((v1, v2)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [49]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)
print(a.T)
print(a)
print(np.swapaxes(a, 0, 1))
print(a.shape)
t1 = np.swapaxes(a, 0, 1)
print(t1)
print(t1.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(3, 4)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [52]:
t3 = np.arange(60).reshape(3, 4, 5)
print(t3)
print('-' * 50)
t4 = np.swapaxes(t3, 0, 1)
print(t4)
print(t4.shape)
t5 = np.swapaxes(t4, 0, 2)
print(t5)
print(t5.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
--------------------------------------------------
[[[ 0  1  2  3  4]
  [20 21 22 23 24]
  [40 41 42 43 44]]

 [[ 5  6  7  8  9]
  [25 26 27 28 29]
  [45 46 47 48 49]]

 [[10 11 12 13 14]
  [30 31 32 33 34]
  [50 51 52 53 54]]

 [[15 16 17 18 19]
  [35 36 37 38 39]
  [55 56 57 58 59]]]
(4, 3, 5)
[[[ 0  5 10 15]
  [20 25 30 35]
  [40 45 50 55]]

 [[ 1  6 11 16]
  [21 26 31 36]
  [41 46 51 56]]

 [[ 2  7 12 17]
  [22 27 32 37]
  [42 47 52 57]]

 [[ 3  8 13 18]
  [23 28 33 38]
  [43 48 53 58]]

 [[ 4  9 14 19]
  [24 29 34 39]
  [44 49 54 59]]]
(5, 3, 4)


In [53]:
t3 = np.arange(60).reshape(3, 4, 5)
t4 = np.rollaxis(t3, 2, start=0)
print(t4.shape)

(5, 3, 4)
