In [29]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import jieba
import numpy as np
import pandas as pd

In [14]:
dict_vectorizer = DictVectorizer(sparse=False)
data = dict_vectorizer.fit_transform([{'city': '北京', 'temperature': 100},
                                      {'city': '上海', 'temperature': 80},
                                      {'city': '广州', 'temperature': 60}])
print(data)
print(type(data))
print(dict_vectorizer.get_feature_names_out())
print(type(dict_vectorizer.inverse_transform(data)))
print(dict_vectorizer.inverse_transform(data))

[[  0.   1.   0. 100.]
 [  1.   0.   0.  80.]
 [  0.   0.   1.  60.]]
<class 'numpy.ndarray'>
['city=上海' 'city=北京' 'city=广州' 'temperature']
<class 'list'>
[{'city=北京': np.float64(1.0), 'temperature': np.float64(100.0)}, {'city=上海': np.float64(1.0), 'temperature': np.float64(80.0)}, {'city=广州': np.float64(1.0), 'temperature': np.float64(60.0)}]


In [23]:

text_vectorizer = CountVectorizer(min_df=1)  # min_df默认为1
text_data = text_vectorizer.fit_transform(["life is  short,i like python life",
                                           "life is too long,i dislike python",
                                           "life is short"])
print(text_vectorizer.get_feature_names_out())
print(text_data)
print(type(text_data))
print(text_data.toarray())
print(text_vectorizer.inverse_transform(text_data))

['dislike' 'is' 'life' 'like' 'long' 'python' 'short' 'too']
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14 stored elements and shape (3, 8)>
  Coords	Values
  (0, 2)	2
  (0, 1)	1
  (0, 6)	1
  (0, 3)	1
  (0, 5)	1
  (1, 2)	1
  (1, 1)	1
  (1, 5)	1
  (1, 7)	1
  (1, 4)	1
  (1, 0)	1
  (2, 2)	1
  (2, 1)	1
  (2, 6)	1
<class 'scipy.sparse._csr.csr_matrix'>
[[0 1 2 1 0 1 1 0]
 [1 1 1 0 1 1 0 1]
 [0 1 1 0 0 0 1 0]]
[array(['life', 'is', 'short', 'like', 'python'], dtype='<U7'), array(['life', 'is', 'python', 'too', 'long', 'dislike'], dtype='<U7'), array(['life', 'is', 'short'], dtype='<U7')]


In [26]:
text_vectorizer2 = CountVectorizer(min_df=1)
text_data2 = text_vectorizer2.fit_transform(["人生苦短，我 喜欢 python python", "人生漫长，不用 python"])
print(text_vectorizer2.get_feature_names_out())
print(text_data2.toarray())
print(text_data2)

['python' '不用' '人生漫长' '人生苦短' '喜欢']
[[2 0 0 1 1]
 [1 1 1 0 0]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6 stored elements and shape (2, 5)>
  Coords	Values
  (0, 3)	1
  (0, 4)	1
  (0, 0)	2
  (1, 0)	1
  (1, 2)	1
  (1, 1)	1


In [46]:
sen1 = jieba.cut("今天很残酷，明天更残酷，后天很美好，但绝对大部分是死在明天晚上，所以每个人不要放弃今天。")
sen2 = jieba.cut("我们看到的从很远星系来的光是在几百万年之前发出的，这样当我们看到宇宙时，我们是在看它的过去。")
sen3 = jieba.cut(
    "如果只用一种方式了解某样事物，你就不会真正了解它。了解事物真正含义的秘密取决于如何将其与我们所了解的事物相联系。")

print(type(sen1))
s1 = list(sen1)
print(s1)
s2 = list(sen2)
print(s2)
s3 = list(sen3)
print(s3)
st1 = ' '.join(s1)
st2 = ' '.join(s2)
st3 = ' '.join(s3)
print(st1)
print(st2)
print(st3)
print('-' * 100)
text_vectorizer3 = CountVectorizer()
data = text_vectorizer3.fit_transform([st1, st2, st3])
print(text_vectorizer3.get_feature_names_out())
print(data.toarray())


<class 'generator'>
['今天', '很', '残酷', '，', '明天', '更', '残酷', '，', '后天', '很', '美好', '，', '但', '绝对', '大部分', '是', '死', '在', '明天', '晚上', '，', '所以', '每个', '人', '不要', '放弃', '今天', '。']
['我们', '看到', '的', '从', '很', '远', '星系', '来', '的', '光是在', '几百万年', '之前', '发出', '的', '，', '这样', '当', '我们', '看到', '宇宙', '时', '，', '我们', '是', '在', '看', '它', '的', '过去', '。']
['如果', '只用', '一种', '方式', '了解', '某样', '事物', '，', '你', '就', '不会', '真正', '了解', '它', '。', '了解', '事物', '真正', '含义', '的', '秘密', '取决于', '如何', '将', '其', '与', '我们', '所', '了解', '的', '事物', '相', '联系', '。']
今天 很 残酷 ， 明天 更 残酷 ， 后天 很 美好 ， 但 绝对 大部分 是 死 在 明天 晚上 ， 所以 每个 人 不要 放弃 今天 。
我们 看到 的 从 很 远 星系 来 的 光是在 几百万年 之前 发出 的 ， 这样 当 我们 看到 宇宙 时 ， 我们 是 在 看 它 的 过去 。
如果 只用 一种 方式 了解 某样 事物 ， 你 就 不会 真正 了解 它 。 了解 事物 真正 含义 的 秘密 取决于 如何 将 其 与 我们 所 了解 的 事物 相 联系 。
----------------------------------------------------------------------------------------------------
['一种' '不会' '不要' '之前' '了解' '事物' '今天' '光是在' '几百万年' '发出' '取决于' '只用' '后天' '含义'
 '大部分' '如何' '如果' '宇宙' '我们' '所以' '放弃' '方式' '明天' '星

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
TV = TfidfVectorizer()
data = TV.fit_transform([st1, st2, st3])
print(TV.get_feature_names_out())
print(data.toarray())

['一种' '不会' '不要' '之前' '了解' '事物' '今天' '光是在' '几百万年' '发出' '取决于' '只用' '后天' '含义'
 '大部分' '如何' '如果' '宇宙' '我们' '所以' '放弃' '方式' '明天' '星系' '晚上' '某样' '残酷' '每个'
 '看到' '真正' '秘密' '绝对' '美好' '联系' '过去' '这样']
[[0.         0.         0.21821789 0.         0.         0.
  0.43643578 0.         0.         0.         0.         0.
  0.21821789 0.         0.21821789 0.         0.         0.
  0.         0.21821789 0.21821789 0.         0.43643578 0.
  0.21821789 0.         0.43643578 0.21821789 0.         0.
  0.         0.21821789 0.21821789 0.         0.         0.        ]
 [0.         0.         0.         0.2410822  0.         0.
  0.         0.2410822  0.2410822  0.2410822  0.         0.
  0.         0.         0.         0.         0.         0.2410822
  0.55004769 0.         0.         0.         0.         0.2410822
  0.         0.         0.         0.         0.48216441 0.
  0.         0.         0.         0.         0.2410822  0.2410822 ]
 [0.15698297 0.15698297 0.         0.         0.62793188 0.