In [7]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import jieba
import numpy as np
import pandas as pd

In [20]:
dict_vectorizer = DictVectorizer(sparse=True)
data = dict_vectorizer.fit_transform([{'city': '北京', 'temperature': 100},
                                      {'city': '上海', 'temperature': 80},
                                      {'city': '广州', 'temperature': 60}])
print(data)
print(type(data))
print(dict_vectorizer.get_feature_names_out())
print(type(dict_vectorizer.inverse_transform(data)))
print(dict_vectorizer.inverse_transform(data))
print(data.toarray())

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (3, 4)>
  Coords	Values
  (0, 1)	1.0
  (0, 3)	100.0
  (1, 0)	1.0
  (1, 3)	80.0
  (2, 2)	1.0
  (2, 3)	60.0
<class 'scipy.sparse._csr.csr_matrix'>
['city=上海' 'city=北京' 'city=广州' 'temperature']
<class 'list'>
[{'city=北京': np.float64(1.0), 'temperature': np.float64(100.0)}, {'city=上海': np.float64(1.0), 'temperature': np.float64(80.0)}, {'city=广州': np.float64(1.0), 'temperature': np.float64(60.0)}]
[[  0.   1.   0. 100.]
 [  1.   0.   0.  80.]
 [  0.   0.   1.  60.]]


In [9]:

text_vectorizer = CountVectorizer(min_df=1)  # min_df默认为1
text_data = text_vectorizer.fit_transform(["life is  short,i like python life",
                                           "life is too long,i dislike python",
                                           "life is short"])
print(text_vectorizer.get_feature_names_out())
print(text_data)
print(type(text_data))
print(text_data.toarray())
print(text_vectorizer.inverse_transform(text_data))

['dislike' 'is' 'life' 'like' 'long' 'python' 'short' 'too']
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14 stored elements and shape (3, 8)>
  Coords	Values
  (0, 2)	2
  (0, 1)	1
  (0, 6)	1
  (0, 3)	1
  (0, 5)	1
  (1, 2)	1
  (1, 1)	1
  (1, 5)	1
  (1, 7)	1
  (1, 4)	1
  (1, 0)	1
  (2, 2)	1
  (2, 1)	1
  (2, 6)	1
<class 'scipy.sparse._csr.csr_matrix'>
[[0 1 2 1 0 1 1 0]
 [1 1 1 0 1 1 0 1]
 [0 1 1 0 0 0 1 0]]
[array(['life', 'is', 'short', 'like', 'python'], dtype='<U7'), array(['life', 'is', 'python', 'too', 'long', 'dislike'], dtype='<U7'), array(['life', 'is', 'short'], dtype='<U7')]


In [10]:
text_vectorizer2 = CountVectorizer(min_df=1)
text_data2 = text_vectorizer2.fit_transform(["人生苦短，我 喜欢 python python", "人生漫长，不用 python"])
print(text_vectorizer2.get_feature_names_out())
print(text_data2.toarray())
print(text_data2)

['python' '不用' '人生漫长' '人生苦短' '喜欢']
[[2 0 0 1 1]
 [1 1 1 0 0]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6 stored elements and shape (2, 5)>
  Coords	Values
  (0, 3)	1
  (0, 4)	1
  (0, 0)	2
  (1, 0)	1
  (1, 2)	1
  (1, 1)	1


In [11]:
sen1 = jieba.cut("今天很残酷，明天更残酷，后天很美好，但绝对大部分是死在明天晚上，所以每个人不要放弃今天。")
sen2 = jieba.cut("我们看到的从很远星系来的光是在几百万年之前发出的，这样当我们看到宇宙时，我们是在看它的过去。")
sen3 = jieba.cut(
    "如果只用一种方式了解某样事物，你就不会真正了解它。了解事物真正含义的秘密取决于如何将其与我们所了解的事物相联系。")

print(type(sen1))
# print(sen1)
s1 = list(sen1)
print(s1)
s2 = list(sen2)
print(s2)
s3 = list(sen3)
print(s3)
st1 = ' '.join(s1)
st2 = ' '.join(s2)
st3 = ' '.join(s3)
print(st1)
print(st2)
print(st3)
print('-' * 100)
text_vectorizer3 = CountVectorizer()
print(type(text_vectorizer3))
data = text_vectorizer3.fit_transform([st1, st2, st3])
print(text_vectorizer3.get_feature_names_out())
print('-' * 100)
print(type(data))
print(data)
print(data.toarray())


Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/lk/8ddg82lx22j4q109wghqhxlm0000gn/T/jieba.cache


<class 'generator'>


Loading model cost 0.306 seconds.
Prefix dict has been built successfully.


['今天', '很', '残酷', '，', '明天', '更', '残酷', '，', '后天', '很', '美好', '，', '但', '绝对', '大部分', '是', '死', '在', '明天', '晚上', '，', '所以', '每个', '人', '不要', '放弃', '今天', '。']
['我们', '看到', '的', '从', '很', '远', '星系', '来', '的', '光是在', '几百万年', '之前', '发出', '的', '，', '这样', '当', '我们', '看到', '宇宙', '时', '，', '我们', '是', '在', '看', '它', '的', '过去', '。']
['如果', '只用', '一种', '方式', '了解', '某样', '事物', '，', '你', '就', '不会', '真正', '了解', '它', '。', '了解', '事物', '真正', '含义', '的', '秘密', '取决于', '如何', '将', '其', '与', '我们', '所', '了解', '的', '事物', '相', '联系', '。']
今天 很 残酷 ， 明天 更 残酷 ， 后天 很 美好 ， 但 绝对 大部分 是 死 在 明天 晚上 ， 所以 每个 人 不要 放弃 今天 。
我们 看到 的 从 很 远 星系 来 的 光是在 几百万年 之前 发出 的 ， 这样 当 我们 看到 宇宙 时 ， 我们 是 在 看 它 的 过去 。
如果 只用 一种 方式 了解 某样 事物 ， 你 就 不会 真正 了解 它 。 了解 事物 真正 含义 的 秘密 取决于 如何 将 其 与 我们 所 了解 的 事物 相 联系 。
----------------------------------------------------------------------------------------------------
<class 'sklearn.feature_extraction.text.CountVectorizer'>
['一种' '不会' '不要' '之前' '了解' '事物' '今天' '光是在' '几百万年' '发出' '取决于' '只用' '后天' '含义'
 '大部分' '如何'

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

TV = TfidfVectorizer()
data = TV.fit_transform([st1, st2, st3])
print(TV.get_feature_names_out())
print(data.toarray())

['一种' '不会' '不要' '之前' '了解' '事物' '今天' '光是在' '几百万年' '发出' '取决于' '只用' '后天' '含义'
 '大部分' '如何' '如果' '宇宙' '我们' '所以' '放弃' '方式' '明天' '星系' '晚上' '某样' '残酷' '每个'
 '看到' '真正' '秘密' '绝对' '美好' '联系' '过去' '这样']
[[0.         0.         0.21821789 0.         0.         0.
  0.43643578 0.         0.         0.         0.         0.
  0.21821789 0.         0.21821789 0.         0.         0.
  0.         0.21821789 0.21821789 0.         0.43643578 0.
  0.21821789 0.         0.43643578 0.21821789 0.         0.
  0.         0.21821789 0.21821789 0.         0.         0.        ]
 [0.         0.         0.         0.2410822  0.         0.
  0.         0.2410822  0.2410822  0.2410822  0.         0.
  0.         0.         0.         0.         0.         0.2410822
  0.55004769 0.         0.         0.         0.         0.2410822
  0.         0.         0.         0.         0.48216441 0.
  0.         0.         0.         0.         0.2410822  0.2410822 ]
 [0.15698297 0.15698297 0.         0.         0.62793188 0.

In [13]:
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler(feature_range=(0, 1))
data = mm.fit_transform([[90, 2, 10, 40], [60, 4, 15, 45], [75, 3, 13, 46]])
print(type(data))
print(data)
print('-' * 80)
print(mm.get_feature_names_out())

<class 'numpy.ndarray'>
[[1.         0.         0.         0.        ]
 [0.         1.         1.         0.83333333]
 [0.5        0.5        0.6        1.        ]]
--------------------------------------------------------------------------------
['x0' 'x1' 'x2' 'x3']


In [14]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()
data = standard_scaler.fit_transform([[90, 2, 10, 40],
                                      [60, 4, 15, 45],
                                      [75, 3, 13, 46]])
print(data)
print(standard_scaler.mean_)
print(standard_scaler.var_)
print('-' * 80)
data2 = standard_scaler.fit_transform([[-1.06904497, -1.35873244, 0.98058068],
                                       [-0.26726124, 0.33968311, 0.39223227],
                                       [1.33630621, 1.01904933, -1.37281295]])
print(standard_scaler.mean_)
print(standard_scaler.var_)

[[ 1.22474487 -1.22474487 -1.29777137 -1.3970014 ]
 [-1.22474487  1.22474487  1.13554995  0.50800051]
 [ 0.          0.          0.16222142  0.88900089]]
[75.          3.         12.66666667 43.66666667]
[150.           0.66666667   4.22222222   6.88888889]
--------------------------------------------------------------------------------
[0. 0. 0.]
[1.         1.         1.00000001]


# 缺失值处理

In [15]:
from sklearn.impute import SimpleImputer

impute = SimpleImputer(missing_values=np.nan, strategy='mean')
data_impute = impute.fit_transform([[1, 2], [np.nan, 3], [7, 6], [3, 2]])
print(data_impute)

[[1.         2.        ]
 [3.66666667 3.        ]
 [7.         6.        ]
 [3.         2.        ]]


# 方差阀值

In [16]:
from sklearn.feature_selection import VarianceThreshold

variance = VarianceThreshold(threshold=0)
data_variance = variance.fit_transform([[0, 2, 0, 3],
                                        [0, 1, 4, 3],
                                        [0, 1, 1, 3]])
print(data_variance)
print('the support is %s' % variance.get_support(True))

[[2 0]
 [1 4]
 [1 1]]
the support is [1 2]


# 降维

In [17]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
data_pca = pca.fit_transform([[2, 8, 4, 5],
                   [6, 3, 0, 8],
                   [5, 4, 9, 1]])
print(data_pca)

[[-9.33473422e-16  3.82970843e+00]
 [-5.74456265e+00 -1.91485422e+00]
 [ 5.74456265e+00 -1.91485422e+00]]
